version: 2
jobs:
  build:
    resource_class: xlarge
    docker:
      - image: wsmoses/tapir:latest

    steps:
      - checkout
      - run:
          name: submodules
          command: |
            git submodule sync
            git submodule update --init --recursive
      - run:
          name: cmake
          command: |
            mkdir build
            cd build
            cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=host -DLLVM_BUILD_TESTS=ON -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_LTO=OFF
      - run:
          name: ninja
          command: |
            cd build
            ninja
      - run:
          name: test
          command: |
            cd build
            ninja check-all
